In [59]:
from google.colab import files
df = files.upload()

Saving Crop recommendation dataset new.csv to Crop recommendation dataset new (1).csv

In [36]:
import pandas as pd

df = pd.read_csv("Crop recommendation dataset new.csv", encoding='latin-1')

In [37]:
df = df.dropna()

In [38]:
df

             CROPS              SOIL  SEASON  TEMP  HUMIDITY
0             Rice     Alluvial soil   Rainy  26.9      73.8
1             Rice        Loamy soil   Rainy  35.8      60.9
2             Rice         Clay soil   Rainy  34.9      67.5
3             Rice     Alluvial soil   Rainy  28.3      73.6
4             Rice        Loamy soil   Rainy  26.3      60.3
...            ...               ...     ...   ...       ...
56995  Small onion  Sandy loamy soil  Summer  21.7      66.0
56996  Small onion  Sandy loamy soil  Summer  20.5      66.2
56997  Small onion  Sandy loamy soil  Summer  18.6      65.6
56998  Small onion  Sandy loamy soil  Summer  23.1      74.2
56999  Small onion  Sandy loamy soil  Summer  20.6      72.1

[57000 rows x 5 columns]

In [39]:
print(df['CROPS'].unique())

['Rice' 'Wheat' 'Maize' 'Sorghum' 'Pearl millet' 'Ragi' 'Panivaragu'
 'Samai' 'Thinai' 'Varagu' 'Kudiraivali' 'Blackgram' 'Greengram' 'Cowpea'
 'Bengalgram' 'Horsegram' 'Redgram' 'Soyabean' 'Groundnut' 'Sunflower'
 'Gingely' 'Castor' 'Cotton' 'Jute' 'Sugarcane' 'Sugarbeet' 'Tomato'
 'Onion' 'Chillies' 'Cabbage' 'Bhendi' 'Brinjal' 'Capsicum' 'Pumpkin'
 'Snake gourd' 'Ribbed gourd' 'Bottle gourd' 'Bitter gourd' 'Ash gourd'
 'Cucumber' 'Watermelon' 'Muskmelon' 'Tinda' 'Chowchow' 'Cluster bean'
 'Vegetable cowpea' 'French bean' 'Peas' 'Annual moringa' 'Carrot'
 'Beetroot' 'Radish' 'Sweet potato' 'Tapoica' 'Elephant foot yam'
 'Cauliflower' 'Small onion']

In [40]:
df['SEASON'].unique()

array(['Rainy', 'Winter', 'Summer'], dtype=object)

In [41]:
from sklearn.preprocessing import LabelEncoder

le_soil = LabelEncoder()
le_season = LabelEncoder()
le_crop = LabelEncoder()

df['SOIL'] = le_soil.fit_transform(df['SOIL'])
df['SEASON'] = le_season.fit_transform(df['SEASON'])
df['CROPS'] = le_crop.fit_transform(df['CROPS'])

df

       CROPS  SOIL  SEASON  TEMP  HUMIDITY
0         39     0       0  26.9      73.8
1         39    15       0  35.8      60.9
2         39     6       0  34.9      67.5
3         39     0       0  28.3      73.6
4         39    15       0  26.3      60.3
...      ...   ...     ...   ...       ...
56995     41    24       1  21.7      66.0
56996     41    24       1  20.5      66.2
56997     41    24       1  18.6      65.6
56998     41    24       1  23.1      74.2
56999     41    24       1  20.6      72.1

[57000 rows x 5 columns]

In [42]:
X = df[['SOIL', 'SEASON', 'TEMP', 'HUMIDITY']]
y = df['CROPS']

In [44]:
X

       SOIL  SEASON  TEMP  HUMIDITY
0         0       0  26.9      73.8
1        15       0  35.8      60.9
2         6       0  34.9      67.5
3         0       0  28.3      73.6
4        15       0  26.3      60.3
...     ...     ...   ...       ...
56995    24       1  21.7      66.0
56996    24       1  20.5      66.2
56997    24       1  18.6      65.6
56998    24       1  23.1      74.2
56999    24       1  20.6      72.1

[57000 rows x 4 columns]

In [45]:
y

0        39
1        39
2        39
3        39
4        39
         ..
56995    41
56996    41
56997    41
56998    41
56999    41
Name: CROPS, Length: 57000, dtype: int64

In [46]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [47]:
from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier(
    n_estimators=200,
    max_depth=10,
    random_state=42
)

model.fit(X_train, y_train)

RandomForestClassifier(max_depth=10, n_estimators=200, random_state=42)

In [48]:
from sklearn.metrics import accuracy_score

y_pred = model.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred))

Accuracy: 0.8542982456140351

In [55]:
soil = input("Enter Soil Type: ")
season = input("Enter Season: ")
temp = float(input("Enter Temperature: "))
humidity = float(input("Enter Humidity: "))

soil_encoded = le_soil.transform([soil])[0]
season_encoded = le_season.transform([season])[0]

input_data = [[soil_encoded, season_encoded, temp, humidity]]

probs = model.predict_proba(input_data)[0]

top3 = probs.argsort()[-3:][::-1]

print("🌱 Top 3 Recommended Crops:")

for i in top3:
    print(le_crop.inverse_transform([i])[0])

Enter Soil Type: Loamy soil
Enter Season: Rainy
Enter Temperature: 35
Enter Humidity: 60
🌱 Top 3 Recommended Crops:
Rice
Cucumber
Sorghum

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(

In [53]:
import joblib

joblib.dump(model, "crop_model.pkl")
joblib.dump(le_soil, "soil_encoder.pkl")
joblib.dump(le_season, "season_encoder.pkl")
joblib.dump(le_crop, "crop_encoder.pkl")

['crop_encoder.pkl']

In [54]:
from google.colab import files

files.download("crop_model.pkl")
files.download("soil_encoder.pkl")
files.download("season_encoder.pkl")
files.download("crop_encoder.pkl")